### PR TITLE
Update version ranges and add README

### PR DESCRIPTION
**Pull request by mschristiansen**
I've updated library versions to work with current version of Purescript and added a README with instructions for the example.

Is there a reason this library is not on Pursuit or would you mind if I look into adding it?

### CODE REVIEW

**Comment by mschristiansen** [comment]
Also just added a `close` function.

**Comment by MichaelXavier** [comment]
Wow, thanks for the PR, I appreciate it! I actually don't remember the status of this package. I think I wrote it while exploring the SSE API and then probably got involved with another yak shave at some point. Have you actually used this project in anything or are you familiar enough with the spec to know if this a reasonably complete MVP of the eventsource spec? If this is a viable and useful library, I'd be interested in releasing it, I just don't know what exactly I need to do.

**Comment by mschristiansen** [comment]
I have a smaller project at work where I would like to use it and have just got it working with Halogen. Haven't systematically compared it with the SSE API, but if anything is missing it can't be much, also considering that the SSE API is very small.

I'm not sure of the process for releasing it on Pursuit, but don't mind looking into it and might also do a library for `purescript-halogen-sse` -- that won't take much code, but it was rather complicated to figure out.

I can look into doing a PR for a release in a day or two when I've exercised it a bit more in my project.

**Comment by MichaelXavier** [comment]
Sure, just let me know how it goes. Thanks for putting some mileage on this library!

**Pull request merged**
